### ISSUE TITLE
Errors in DQI calculation when total requirements are negative

### ISSUE THREAD

**Issue by MoLi7** [USEPA/useeiopy#2]
- Last two column names of L, M_dqi, M, U_dqi, and U are incorrect: **used/farms/us** and **other/forestry, fishing, and related activities/us**
- DQ scores for N2O for GFGN and Other are incorrect: (6, 2, 1, 10, 1).

Errors could be caused when [adding matrices](https://github.com/USEPA/useeiopy/blob/e56e53410c1f62d684fdeb2f05606b8e69c48232/useeiopy/__init__.py#L30).
@WesIngwersen could you review it? Thanks!

**Comment by WesIngwersen** [comment]
@MoLi7 Yes the origin of this issue is in A where there is a negative direct requirement which leads to a negative total requirement in L. This is valid (I think) because it comes directly from the table. However the issues is that the DQI algorithm needs to be modified to handle this .. what is happening is that the DQI values for that cell are positive, and the flow values are negative...the sume of the flow values is the divisor (it's a weighted average) so we end up with a problem. I am renaming this issue appropriatly to be more specific.

**Comment by WesIngwersen** [comment]
This is related if not identical to this issue. [IO-Model-Builder #12](https://github.com/USEPA/IO-Model-Builder/issues/12)

**Comment by WesIngwersen** [comment]
Resolved linked issue in IO-Model-Builder. Updated iomb requirement to use a release of iomb where this is resolved.
